services:
  - type: web
    name: nexusbot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: SESSION_ID
        sync: false
      - key: WHATSAPP_PHONE_NUMBER
        sync: false